services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: wordpress
  wordpress:
    depends_on:
      - db
    image: butavicius/wordpress-test
    volumes:
      - ./wp-themes:/var/www/html/wp-content/themes
      - ./wp-plugins:/var/www/html/wp-content/plugins
      - ./apache-sites-enabled:/etc/apache2/sites-enabled
      - certbot_data:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always
    env_file:
      - ./.env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
volumes:
  certbot_data: null
  db_data: null
