#!/bin/bash

set -e

_stop() {
    /etc/init.d/postfix stop
    /etc/init.d/rsyslog stop
    echo "Postfix init script stopped"
}

trap "_stop" SIGINT SIGTERM SIGHUP

# Configure mail relay host
if [ -n "$MAIL_RELAY_HOST" ] && [ -n "$MAIL_RELAY_USER" ] && [ -n "$MAIL_RELAY_PASS" ] && [ -n "$MAIL_RELAY_PORT" ]; then
    postconf -e relayhost="$MAIL_RELAY_HOST:$MAIL_RELAY_PORT"
    echo "$MAIL_RELAY_HOST $MAIL_RELAY_USER:$MAIL_RELAY_PASS" > /etc/postfix/sasl_passwd
    postmap /etc/postfix/sasl_passwd
else
    echo '$MAIL_RELAY_PORT, $MAIL_RELAY_HOST, $MAIL_RELAY_USER or $MAIL_RELAY_PASS is not set. Can not configure postfix. Exiting'
    exit 1
fi

# Start syslog daemon
/etc/init.d/rsyslog start

# Start Postfix daemon
/etc/init.d/postfix start

# Start wordpress
/usr/local/bin/docker-entrypoint.sh apache2-foreground