#!/bin/bash

set -e

_add_line() {
    local check="$1"
    local line="$2"
    local file="$3"
    if ! grep -q "$check" "$file"; then
        echo "$line" >> "$file"
    fi
}

_log() {
    local logfile=/var/log/mail.log
    if [ ! -f $logfile ]; then
        touch $logfile
        chmod 640 $logfile
    fi
    echo "$(date '+%b %e %H:%I:%S') $(hostname) entrypoint[$$]: $1" >> $logfile
}

_stop() {
    /etc/init.d/postfix stop
    /etc/init.d/rsyslog stop
    _log "Postfix init script stop"
}

trap "_stop" SIGINT SIGTERM SIGHUP

_log "Postfix init script start"

apt-get update && \
apt-get upgrade -yqq && \
echo "postfix postfix/mailname string $MAILNAME" | debconf-set-selections && \
echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections && \
apt-get install -yqq postfix rsyslog iproute2 wget libsasl2-modules && \
apt-get clean -yqq && \
apt-get autoclean -yqq && \
apt-get autoremove -yqq && \
rm -rf /var/cache/apt/archives/* /var/cache/apt/*.bin /var/lib/apt/lists/* && \
update-ca-certificates

chmod a+rx /usr/local/bin/* && \
postconf -e smtp_tls_CAfile=/etc/ssl/certs/ca-certificates.crt && \
postconf -e smtp_tls_security_level=may && \
postconf -e smtp_sasl_auth_enable=yes && \
postconf -e smtp_sasl_password_maps=hash:/etc/postfix/sasl_passwd && \
postconf -e smtp_sasl_security_options=noanonymous

# Mail relay host
if [ -n "$MAIL_RELAY_HOST" ] && [ -z "$MAIL_RELAY_PORT" ]; then
    postconf -e relayhost=$MAIL_RELAY_HOST;
fi
if [ -n "$MAIL_RELAY_HOST" ] && [ -n "$MAIL_RELAY_PORT" ]; then
    postconf -e relayhost="$MAIL_RELAY_HOST:$MAIL_RELAY_PORT";
fi
if [ -n "$MAIL_RELAY_HOST" ] && [ -n "$MAIL_RELAY_USER" ] && [ -n "$MAIL_RELAY_PASS" ]; then
    touch /etc/postfix/sasl_passwd
    _add_line "$MAIL_RELAY_HOST" "$MAIL_RELAY_HOST $MAIL_RELAY_USER:$MAIL_RELAY_PASS" /etc/postfix/sasl_passwd
    postmap /etc/postfix/sasl_passwd
else
    echo '$MAIL_RELAY_HOST, $MAIL_RELAY_USER or $MAIL_RELAY_PASS is not set. Can not configure postfix. Exiting';
    exit 1;
fi

_log "Postfix init script configured"

# Start syslog daemon
/etc/init.d/rsyslog start

# Start Postfix daemon
/etc/init.d/postfix start

$@ & wait ${!}